* Introduction
  
  Le backlog est réalisé sur la solution logiciel Waffle.io, qui est un outil de développement de projets fonctionnait en lien avec GitHub.

  Lien: https://github.com/AlEmerich/ConduitePhase2

* Backlog

| number | description                                                                                                                                             | effort | priority |
|--------+---------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------|
|      1 | En tant que visiteur, je souhaite pouvoir m'inscrire ou me connecter en tant que utilisateur.                                                           |      3 |        1 |
|      2 | En tant que utilisateur, je souhaite pouvoir créer mes propres projets.                                                                                 |      5 |        1 |
|      3 | En tant que utilisateur, je souhaite pouvoir lister mes projets, afin de les modifier ou de les supprimer.                                              |      3 |        2 |
|      4 | En tant que utilisateur, je souhaite pouvoir créer des User Stories dans le backlog.                                                                    |      2 |        2 |
|      5 | En tant que utilisateur, je souhaite pouvoir lister ces User Stories afin de les modifier ou de les supprimer.                                          |      3 |        2 |
|      6 | En tant que product owner, je souhaite pouvoir modifier la priorité des User Stories.                                                                   |      3 |        2 |
|      7 | En tant que utilisateur, je souhaite pouvoir planifier des sprints avec des User Stories déjà entrées.                                                  |      5 |        3 |
|      8 | En tant que utilisateur, je souhaite pouvoir éditer le planning afin de préciser quelles User Story sont développpés à un moment donné.                 |      2 |        3 |
|      9 | En tant que utilisateur, je souhaite pouvoir inviter d’autres utilisateur à contribuer aux projets afin que ces derniers aient les mêmes privilèges.   |      1 |        1 |
|     10 | En tant que utilisateur, je souhaite pouvoir définir un product owner parmi les contributeurs afin qu'il puisse modifier la prio des User Stories.      |      2 |        1 |
|     11 | En tant que utilisateur, je souhaite pouvoir créer des tâches associées a une des US déjà créées afin de les lister.                                    |      5 |        3 |
|     12 | En tant que utilisateur, je souhaite pouvoir modifier ou supprimer les tâches déjà créées.                                                              |      3 |        3 |
|     13 | En tant que utilisateur, je souhaite pouvoir modifier le kanban d'un sprint en fonction de leur état de développement.                                  |      5 |        3 |
|     14 | En tant que utilisateur, je souhaite pouvoir modifier la matrice de tracabilité afin de savoir à quel commit une US a été traitée.                      |      2 |        3 |
|     15 | En tant que utilisateur, je souhaite pouvoir accéder au différents sprints du projet afin d'en voir les évolutions.                                     |      3 |        3 |
|     16 | En tant que utilisateur, je souhaite pouvoir accéder facilement utiles aux dépôts du projet (dépôt, README, doc).                                       |      1 |        2 |
|     17 | En tant que utilisateur, je souhaite voir la courbe de vélocité du projet.                                                                              |      1 |        3 |
|--------+---------------------------------------------------------------------------------------------------------------------------------------------------------+--------+----------|
|        | Coût total                                                                                                                                              |     50 |          |

* Planning

** Sprint 1

   Création d'un statut utilisateur, des projets et de leur gestion et création de User Stories.
   
   #US 1, 2, 3, 4, 5
   rework: #US 1,2,3,4,9,10
   resultat final: #US 1,2
   Effort : 16

*** Tâches 

**** All

Création Base de donnée
Création page d'accueil qui affiche tout les projets
Ajout de fonction dans CtrlProject.php: listAll()

**** User Story 1

***** SQL Tâche 1
      Création table Utilisateur: Nom, mdp, mail
***** View Tâche 2
      Création page incription.php qui invite à entrer login, mail et mdp
      Création page connexion.php qui invite à entrer son mail et mdp
***** Ctrl Tâche 3
      Ajout des requêtes SQL d'ajout d'utilisateur dans un fichier Php CtrlUser.php:
- fonction addUser(nom, mail, mdp)
- fonction isUser(mail, mdp)

**** User Story 2

***** SQL Tâche 4
      Création table Project: Nom du projet, membres, product owner, lien du dépôt
      Création table Participe faisant le lien avec User
***** View Tâche 5
      Création page createProject.php qui invite à entrer Nom du projet, lien du dépôt
***** Ctrl Tâche 6
      Ajout des requêtes SQL de création de projet dans un fichier Php CtrlProject.php:
- fonction createProject(Nom,link,user)

**** User Story 3

***** View Tâche 7
      Création page de listing des projets que l'utilisateur contribue ainsi que ceux qu'il n'y contribue pas.
***** Ctrl Tâche 8
      Ajout de requêtes à CtrlProject.php:
- fonction listIn(login)
- fonction listNotIn(login)

**** User Story 4

***** SQL Tâche 9
      Création table User Stories: project_id,description, effort, priorité
***** View Tâche 10
      Création page d'ajout de user story AccessUserStory.php
***** Ctrl Tâche 11
      Ajout de requête à CtrlBacklog.php:
- fonction addUserStory(description, effort, priorité)
 
**** User Story 9

***** View Tâche 12
      Créer page d'accueil d'un projet ViewProject.php
      ajouter un bouton add user avec menu déroulant dans la page d'accueil du projet.

***** Ctrl Tâche 13
	Ajout d'une requète à CtrlProject.php:
- fonction addUser(userName)

**** User Story 10

***** View Tâche 14
	ajouter bouton avec menu déroulant add product owner sur la page d'accueuil du projet.

***** Ctrl Tâche 15
	Ajout de requète à CtrlProject.php:
- fonction addProductOwner(userName)

**** Tests
     Utilisation de Sélenium pour test de vue
     Tests unitaires pour les controleurs


** Résultat du sprint 1
   
   #US 3, 4, 9, 10 non terminé.


** Sprint 2

Plannification des sprints et documentation associée, invitation aux autres dev et création du statut de product owner, 
création et listing des tâches d'un sprint 

#US 7, 9, 10, 6, 11
rework: #US 5,6,7,8,14,16
après sprint 1: #US 3, 4, 9, 10, 5, 6, 7, 8
Effort : 15->21

*** Tâches

**** All
     tache 18: écriture des tests de complétion des user stories

**** User Story 3 (Rattrapage)

***** View Tâche 1
      Implémentation de la page d'accueil log in et log out:
      - Création page de listing des projets que l'utilisateur contribue ainsi que ceux qu'il n'y contribue pas.
- item de liste cliquable afin d'être redirigé vers homeProject.php

***** Ctrl Tâche 2
      Ajout de requêtes à CtrlProject.php:
- fonction listIn(login)
- fonction listNotIn(login)

**** User Story 4 (Rattrapage)

***** SQL Tâche 3
      Création table User Stories: project_id,description, effort, priorité
***** View Tâche 4
      Création page d'ajout de user story AccessUserStory.php
***** Ctrl Tâche 5
      Ajout de requête à CtrlBacklog.php:
- fonction addUserStory(description, effort, priorité)

**** User Story 9 (Rattrapage)
     
***** SQL tâche 6
      creer table participe recensant tous les participants au projet

***** View Tâche 7
      Créer page d'accueil d'un projet ViewProject.php
      ajouter un bouton add user avec menu déroulant dans la page d'accueil du projet.

***** Ctrl Tâche 8
	Ajout d'une requète à CtrlProject.php:
- fonction addUser(userName)

**** User Story 10 (Rattrapage)

***** View Tâche 9
	ajouter bouton avec menu déroulant add product owner sur la page d'accueuil du projet.

***** Ctrl Tâche 10
	Ajout de requète à CtrlProject.php:
- fonction addProductOwner(userName)

**** User Story 7

***** SQL tâche 11
     Création de la table sprint (cf. ModèleDatabase.png, racine du dépôt)

***** View tâche 12
     Implémenter l'interface sprint comme sur la maquette, en tableau.
     - Ajout, suppression, modification des sprints.

***** Ctrl tâche 13
     Controleur de la table sprint:
     - createSprint(...)
     - updateSprint(...)

**** User Story 5

***** View tâche 14
     implémentation backlog.php afin de lister les user stories du projet

***** Ctrl tâche 15
     Implémenter fonction listUserStories in CtrlBacklog.php

**** User Story 6

***** View tâche 16
      ajouter bouton "changer prio" visible uniquement par le product owner

**** User Story 8

***** View tâche 17
      Dans la page backlog créer un bouton "tache/planning" pour chaque sprint.
      Créer la page planning.php (cf. maquette)
      
** Sprint 3

Edition du planning du projet, modification et suppresion des tâches, Kanban et matrice de tracabilité, overview des sprints 
et courbe de vélocité

#US 8, 12, 13, 14, 15, 16, 17
rework: #US 8, 11,12,13,15,17,16,14
Effort : 22

*** Tâches

**** User Story 8 

***** SQL Tâche 1 
	Créer une table "Tasks" dans notre base de données

***** CTrl Tâche 2
	Créer "CtrlTasks.php" qui fera le lien entre la View et le SQL

**** User Story 11

***** Ctrl tâche 3
	Créer une requête permettant de liste les tâche d'une US

***** View tâche 4
	Modifier la page pour afficher cette liste

**** User Story 12

***** Ctrl tâche 5
	Modifier le contrôleur pour modifier et supprimer une tâche

***** View tâche 6
	Ajouter des boutons pour la modification/suppression

**** User Story 13

***** View tâche 7
	Créer une page kanban.php (tâbleau, boutons permettant de colonnes)

***** SQL tâche 8
	Créer une table "Kanban" permettatn de savoir qui s'occupe d'une tâche et l'état de la tâche

***** Ctrl tâche 9
	Créer un contrôleur permettan d'ajouter et mettre à jour des tâches

**** User Story 14

***** View tâche 10 
	Permettre de voir la matrice de traçabilité dans la page Kanban

***** SQL tâche 11
	Modifier table UserStory pour avoir un numéro de commit à ajouter quand US terminée

***** Ctrl tâche 12
	Modifier CtrlUserStory pour ajouter un numéro de commit

**** User Story 15

***** View tâche 13
	Ajouter une page homeSprint.php

**** User Story 16

***** View tâche 14
	Modifier homeProject pour avoir accès aux infos manquantes

**** User Story 17

***** Ctrl tâche 15
	Ajouter un contrôleur permettant de récupérer les données utiles pour la courbe de vélocité

***** View tâche 16
	Faire en sorte quela courbe se trace en fonction de ces données

***** SQL tâche 17
	Modifier la table relationSprintUS pour ajouter un booléen quipermettra de savoir si une US a bien été terminée dans le sprint correspondant

**** All


***** Tests tâche 18
	Ajouter des tests pour toutes ces fonctionnalités
